@startuml
title ClickerTD Komponenšu Diagramma

skinparam linetype ortho
skinparam componentStyle rectangle
skinparam shadowing false
skinparam ranksep 70
skinparam nodesep 55

left to right direction

package "Saskarnes Slānis" {
  [Līmeņu Izvēles UI]
  [Torņu Uzlabošanas UI]
  [Uzvaras / Zaudējuma UI]
  [HUD UI]
}

package "Progresijas Slānis" {
  [ProgressManager]
  [LevelManager]
  [SceneController]
}

package "Spēles Loģikas Slānis" {
  [RoundManager]
  [EnemySpawner]
  [PlayerCursor]
  [ClickManager]
  [MoneySystem]
  [PlayerHealth]
}

package "Torņu Slānis" {
  [TowerPlace]
  [TowerSelectButton]
  [TowerBuff]
  [Trāpījuma Efekti]
}

package "Pretinieku Slānis" {
  [EnemyMover]
  [EnemyHealth]
  [EnemyManager]
  [Pretinieku Modifikatori]
}

package "Kartes Slānis" {
  [GridManager]
  [Path]
  [ObstaclePath]
  [LevelInitializer]
}

package "Konfigurācijas Resursi" {
  [TowerData Resursi]
  [EndlessModeConfig Resurss]
}

[Līmeņu Izvēles UI] -right-> [LevelManager]
[Līmeņu Izvēles UI] -down-> [ProgressManager]
[Torņu Uzlabošanas UI] -down-> [TowerBuff]
[Uzvaras / Zaudējuma UI] -left-> [SceneController]
[Uzvaras / Zaudējuma UI] -down-> [PlayerHealth]
[HUD UI] -left-> [MoneySystem]
[HUD UI] -left-> [RoundManager]

[LevelManager] -down-> [ProgressManager]
[LevelManager] -right-> [SceneController]
[SceneController] -down-> [RoundManager]

[RoundManager] -right-> [EnemySpawner]
[RoundManager] -down-> [ProgressManager]
[RoundManager] -left-> [EndlessModeConfig Resurss]

[ClickManager] -right-> [PlayerCursor]
[PlayerCursor] -down-> [Trāpījuma Efekti]
[PlayerCursor] -right-> [EnemyHealth]
[TowerPlace] -down-> [GridManager]
[TowerPlace] -right-> [TowerData Resursi]
[TowerSelectButton] -left-> [TowerPlace]
[TowerSelectButton] -down-> [ProgressManager]
[TowerBuff] -left-> [PlayerCursor]
[TowerBuff] -down-> [TowerData Resursi]

[EnemySpawner] -down-> [EnemyMover]
[EnemySpawner] -down-> [EnemyHealth]
[EnemySpawner] -left-> [Path]
[EnemyHealth] -right-> [Pretinieku Modifikatori]
[EnemyHealth] -down-> [MoneySystem]
[EnemyHealth] -down-> [EnemyManager]
[EnemyMover] -left-> [Path]

[LevelInitializer] -left-> [GridManager]
[LevelInitializer] -down-> [Path]
[LevelInitializer] -down-> [ObstaclePath]
[ObstaclePath] -left-> [GridManager]

@enduml
